### PR TITLE
Pass Translator object, now there is a question, how to pass the differe...

### PR DESCRIPTION
**Pull request by harikt**
...nt language, and fallback.

I know probably you have better words. Just a small contribution .

### CODE REVIEW

**Comment by pmjones** [comment]
Great minds think alike: I put exactly that on my personal "todo" list just an hour ago. :-)

**Comment by harikt** [comment]
cool :+1:  .

**Comment by harikt** [comment]
@pmjones I think, here we can do one thing. Don't do the translation, let them use `Aura.Intl` or similar ones if they really need translation. 

Just provide the array values and if they need let them include the `intl/en_US.php` . In that case we can use `echo $message[$label]` where `$label` is the error.

**Comment by harikt** [comment]
That helps to remove the code duplication and the BC break on `Beta1`

**Comment by harikt** [comment]
@pmjones Though the discussion is different the PR if for Readme update .

**Pull request closed without merging**
