### PR TITLE
Test case for issue #99

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by pmjones** [comment]
TAAAAABS

**Comment by pmjones** [comment]
Also, probably needs an assertion in there. :-)

**Comment by harikt** [comment]
Boom... this time you are fast to pick it. The current project was needed tabs so the editor :P .

no assertion needed for the current time for it is always a failure ;) .

**Comment by harikt** [comment]
Regarding failure message I have mentioned it over https://github.com/auraphp/Aura.Filter/issues/99#issuecomment-175737567 . No idea how to move.

**Comment by pmjones** [comment]
Yeah, but when it works, we'll need an assertion of some sort to guard against other failures.

**Pull request merged**
