### PR TITLE
add the rule collection and how to call from controller via setter injec...

### PR DESCRIPTION
**Pull request by harikt**
...tion

### CODE REVIEW

**Comment by harikt** [comment]
What are your thoughts on filter ?

**Comment by pmjones** [comment]
@harikt : A RuleCollection filter object is probably not something we want as a service.  I expect that there will be different models in the system, each one needing its own set RuleCollection for filtering.  (Some might need more than one; e.g., one filter to use on insert, another to use on update, etc.)

**Comment by harikt** [comment]
May be we need a factory to create the filter object ?

**Comment by pmjones** [comment]
Probably not, at least not yet.  What I expect will happen is that the object that needs filtering will receive a new RuleCollection, and then add whatever rules it needs.

**Comment by harikt** [comment]
> object that needs filtering will receive a new RuleCollection, and then
> add whatever rules it needs.

man! are you crazy , add all rules? If we can add it as a closure its not
called right. Then why do we want to force them to add it ?

**Comment by pmjones** [comment]
Either that, or a builder for the object that needs filtering will set up the RuleCollection.  Remember, there are going to be lots of different data objects in the system; they will each need their own filters, with their own rule collections.

**Comment by harikt** [comment]
@pmjones sorry I mixed `RuleLocator` and `RuleCollection`. It was my fault.

**Comment by pmjones** [comment]
Ah yes, I understand. :-)

**Pull request closed without merging**
