### PR TITLE
Documented missing replacement argument of `regex` sanitizer

### PR DESCRIPTION
**Pull request by Rayne**

### CODE REVIEW

**Comment by pmjones** [comment]
Nice! You have any more coming? If so, I can batch them into the same release (I have some time available today/tomorrow).

**Comment by Rayne** [comment]
I just finished reading the whole documentation and this was the only issue I found.

**Comment by harikt** [comment]
@pmjones is there any reason you did not merge this? If not we can merge / fix the documentation issue.

**Comment by pmjones** [comment]
Oh good grief, I thought I _had_ merged it. Will do so and do another release. Thanks!

**Comment by harikt** [comment]
Wait another PR https://github.com/auraphp/Aura.Filter/pull/129 waiting before the release :) .

**Comment by pmjones** [comment]
Thank God for @harikt

**Pull request merged**
