### PR TITLE
Fixed sanitize double rule, when remove all minuses not at the front

### PR DESCRIPTION
**Pull request by frugan-dev**

### CODE REVIEW

**Comment by harikt** [comment]
Hi there, 

Can you write a test for this?

**Comment by harikt** [comment]
I don't see a problem in this current implementation. What makes you think this has a bug ?

**Comment by frugan-dev** [comment]
Hi there,

if $value is a string
https://github.com/auraphp/Aura.Filter/blob/f9720709ddb43f6fe59ed12ebb6537f2a3eeeadf/src/Rule/Sanitize/Double.php#L52
how could it be $value[0] here
https://github.com/auraphp/Aura.Filter/blob/f9720709ddb43f6fe59ed12ebb6537f2a3eeeadf/src/Rule/Sanitize/Double.php#L77
?

$value is not an array..

**Comment by harikt** [comment]
@ewake 

```
$hey = "Hello";

echo $hey[0];
```

You can see the result online :  https://3v4l.org/hrLoE

So nothing wrong right ?

**Comment by frugan-dev** [comment]
Wow, thank you! I didn't know this..
Sorry, happy new year!

**Comment by harikt** [comment]
@ewake Happy New year to you too. Enjoy! .

**Pull request closed without merging**
