### PR TITLE
Add Uuid filter & sanitizer

### PR DESCRIPTION
**Pull request by danielgutenberg**
Adds a UUID filter based on [rfc4122](http://tools.ietf.org/html/rfc4122), including tests.

### CODE REVIEW

**Comment by danielgutenberg** [comment]
BTW, tests are failing for php < 5.5, as php < 5.5 doesn't support the [`CLASS` constant](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class), which was added in https://github.com/auraphp/Aura.Filter/commit/7302ed4d7099e864f64315e3dda9478f4b1d17c4

**Comment by mbrevda** [comment]
Thanks @danielgutenberg, I hope this gets merged soon

**Comment by pmjones** [comment]
Nice. I've been using a custom one at work for v4 only.

**Comment by pmjones** [comment]
As a side note, any reason to remove the dashes from the UUID when sanitizing? I've been leaving them in place for systems like Postgres, and all common examples I see have the dashes in place as well.

**Comment by mbrevda** [comment]
EDIT: you asked about sanitizing, not validating. NM

**Comment by danielgutenberg** [comment]
I guess for sanitizing I probably shouldn't remove the hyphens.  I guess I just wanted it for the validation because at least the class I was using to create the Uuids, [ramsey/uuid](https://github.com/ramsey/uuid), had methods that cut out the hyphens and I think they should still pass the validation.

Is it worth it to pass in an additional parameter to filter for a specific version of uuid?

**Comment by pmjones** [comment]
Let's leave the dashes in place for sanitizing. If you can send a PR for that today I will merge today.

For validation, does having the dashes in the right place actually matter? (I have not dived into the RFC.)

Passing a param for the specific version I think would be useful, at least for validation.

For sanitizing, we don't necessarily want to recreate the entirety of Ramsey's UUID package, but some versions (e.g. v4) are straightforward enough.

**Comment by pmjones** [comment]
E.g. generating a v4 ID is pretty easy:

```
// via http://stackoverflow.com/a/15875555
protected function generate()
{
    // random bytes of data
    $bin = mcrypt_create_iv(16, MCRYPT_DEV_URANDOM);

    // set version to 0100
    $bin[6] = chr(ord($bin[6]) & 0x0f | 0x40);

    // set bits 6-7 to 10
    $bin[8] = chr(ord($bin[8]) & 0x3f | 0x80);

    // convert to hex string
    $hex = bin2hex($bin);

    // split into array elements of max 4 chars each
    $arr = str_split($hex, 4);

    // done
    return vsprintf('%s%s-%s-%s-%s-%s%s%s', $arr);
}
```

**Comment by pmjones** [comment]
Alternatively, extending to a (e.g.) UuidV4 class makes sense too, so that we're not in the business of passing mysterious parameters.

**Comment by danielgutenberg** [comment]
To be compliant with the RFC standard, the position of the hyphens do matter, but if I am going to allow validation to pass with no hyphens I am not sure if it makes sense to have it fail if the hyphens are in the wrong position.  Let me know what you want with that and I can validate if it matches either 1) the pattern with the hyphens in the correct position or 2)  the pattern without hyphens at all.

**Comment by danielgutenberg** [comment]
for now I will keep in the hyphens for sanitizing and send a pull request and for the rest I will wait to hear back from you.

**Pull request merged**
