### PR TITLE
Add hhvm to travis ci

### PR DESCRIPTION
**Pull request by ThomasWunderlich**
Test the hhvm runtime but allow it to fail

### CODE REVIEW

**Comment by harikt** [comment]
I will wait to hear @pmjones for he didn't liked to show the failing test in hhvm. We have discussed this some time later .

**Comment by ThomasWunderlich** [comment]
Sure. That's why I put the allow failure section in as well.

**Comment by pmjones** [comment]
Let's see how this goes. If it works, we can remove the "allow failure" portion.

(FWIW, while I am very interested in v2 being HHVM-compatible, the v1 stuff is not so big a deal to me.)

Thanks @ThomasWunderlich !

**Comment by pmjones** [comment]
Yeah, so it looks like it fails. @ThomasWunderlich thoughts on how to remedy?

**Comment by pmjones** [comment]
Ah, it looks like re-binding a closure to another object is what kills it.

**Pull request merged**
